# Generated by Django 5.2.11 on 2026-02-18 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals_node', '0001_initial'),
        ('reviewer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proposalreviewer',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='proposalreviewer',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewers_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='proposalreviewer',
            constraint=models.UniqueConstraint(fields=('proposal', 'reviewer'), name='unique_proposal_reviewer'),
        ),
    ]
