# Generated by Django 5.2.11 on 2026-02-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0002_alter_proposalreviewer_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalreviewer',
            name='decision',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision', 'Revision Required')], default='pending', max_length=20, null=True),
        ),
    ]
