# Generated by Django 5.2.11 on 2026-03-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0003_proposalreviewer_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalreviewer',
            name='proposal_type',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision', 'Revision Required')], default='program', max_length=100),
        ),
        migrations.AlterField(
            model_name='proposalreviewer',
            name='decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision', 'Revision Required')], default='pending', max_length=20),
        ),
    ]
