# Generated by Django 5.2.11 on 2026-03-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0004_proposalreviewer_proposal_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalreviewer',
            name='proposal_type',
            field=models.CharField(choices=[('program', 'Program'), ('project', 'Project'), ('activity', 'Activity')], default='program', max_length=100),
        ),
    ]
