# Generated by Django 5.2.11 on 2026-02-14 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proposals_node', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_title', models.CharField(blank=True, max_length=255, null=True)),
                ('program_leader', models.CharField(blank=True, max_length=255, null=True)),
                ('projects_list', models.JSONField(blank=True, null=True)),
                ('implementing_agency', models.JSONField(blank=True, null=True)),
                ('cooperating_agencies', models.JSONField(blank=True, null=True)),
                ('extension_sites', models.JSONField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('clusters', models.JSONField(blank=True, null=True)),
                ('agendas', models.JSONField(blank=True, null=True)),
                ('sdg_addressed', models.CharField(blank=True, max_length=255, null=True)),
                ('mandated_academic_program', models.CharField(blank=True, max_length=255, null=True)),
                ('rationale', models.TextField(blank=True, null=True)),
                ('significance', models.TextField(blank=True, null=True)),
                ('general_objectives', models.TextField(blank=True, null=True)),
                ('specific_objectives', models.TextField(blank=True, null=True)),
                ('methodology', models.JSONField(blank=True, null=True)),
                ('expected_output_6ps', models.JSONField(blank=True, null=True)),
                ('sustainability_plan', models.TextField(blank=True, null=True)),
                ('org_and_staffing', models.JSONField(blank=True, null=True)),
                ('workplan', models.JSONField(blank=True, null=True)),
                ('budget_requirements', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='program_details', to='proposals_node.proposal')),
            ],
        ),
    ]
