# Generated by Django 5.2.11 on 2026-02-18 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program_proposal', '0002_programproposalhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programproposalhistory',
            name='projects_list',
        ),
    ]
