# Generated by Django 5.2.11 on 2026-02-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_proposal', '0003_remove_programproposalhistory_projects_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='programproposalhistory',
            name='projects_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
