# Generated by Django 5.2.11 on 2026-02-19 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program_proposal', '0004_programproposalhistory_projects_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programproposalhistory',
            old_name='projects_list',
            new_name='project_list',
        ),
    ]
