# Generated by Django 5.2.11 on 2026-02-19 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program_proposal', '0005_rename_projects_list_programproposalhistory_project_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programproposal',
            old_name='projects_list',
            new_name='project_list',
        ),
    ]
