# Generated by Django 5.2.11 on 2026-03-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_proposal', '0006_rename_projects_list_programproposal_project_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programproposal',
            name='methodology',
            field=models.TextField(blank=True, null=True),
        ),
    ]
