# Generated by Django 5.2.11 on 2026-02-14 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('needs_revision', 'Needs Revision'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('review_round', models.CharField(blank=True, max_length=10, null=True)),
                ('proposal_type', models.CharField(blank=True, choices=[('Program', 'Program'), ('Project', 'Project'), ('Activity', 'Activity')], max_length=20, null=True)),
                ('source_of_fund', models.TextField(blank=True, null=True)),
                ('profile_feedback', models.TextField(blank=True, null=True)),
                ('rationale_feedback', models.TextField(blank=True, null=True)),
                ('significance_feedback', models.TextField(blank=True, null=True)),
                ('objectives_feedback', models.TextField(blank=True, null=True)),
                ('general_objectives_feedback', models.TextField(blank=True, null=True)),
                ('specific_objectives_feedback', models.TextField(blank=True, null=True)),
                ('methodology_feedback', models.TextField(blank=True, null=True)),
                ('expected_output_feedback', models.TextField(blank=True, null=True)),
                ('sustainability_plan_feedback', models.TextField(blank=True, null=True)),
                ('org_staffing_feedback', models.TextField(blank=True, null=True)),
                ('work_plan_feedback', models.TextField(blank=True, null=True)),
                ('budget_requirements_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal_reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_reviewer', to='reviewer.proposalreviewer')),
            ],
        ),
    ]
