# Generated by Django 5.2.11 on 2026-02-18 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalreview',
            name='source_of_fund',
        ),
        migrations.AddField(
            model_name='proposalreview',
            name='Extension_site_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalreview',
            name='implementing_agency_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalreview',
            name='sdg_academic_program_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalreview',
            name='tagging_cluster_extension_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
