# Generated by Django 5.2.11 on 2026-02-18 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_proposalreview_source_of_fund_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposalreview',
            old_name='Extension_site_feedback',
            new_name='extension_site_feedback',
        ),
    ]
