# Generated by Django 5.2.11 on 2026-02-23 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals_node', '0002_alter_proposal_status'),
        ('reviews', '0003_rename_extension_site_feedback_proposalreview_extension_site_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalreview',
            name='proposal_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proposals_node.proposal'),
        ),
    ]
