# Generated by Django 5.2.11 on 2026-02-25 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals_node', '0002_alter_proposal_status'),
        ('reviews', '0004_proposalreview_proposal_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalReviewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(blank=True, choices=[('pending', 'Pending'), ('needs_revision', 'Needs Revision'), ('approved', 'Approved')], max_length=20, null=True)),
                ('review_round', models.CharField(blank=True, max_length=10, null=True)),
                ('profile_feedback', models.TextField(blank=True, null=True)),
                ('implementing_agency_feedback', models.TextField(blank=True, null=True)),
                ('extension_site_feedback', models.TextField(blank=True, null=True)),
                ('tagging_cluster_extension_feedback', models.TextField(blank=True, null=True)),
                ('sdg_academic_program_feedback', models.TextField(blank=True, null=True)),
                ('rationale_feedback', models.TextField(blank=True, null=True)),
                ('significance_feedback', models.TextField(blank=True, null=True)),
                ('objectives_feedback', models.TextField(blank=True, null=True)),
                ('general_objectives_feedback', models.TextField(blank=True, null=True)),
                ('specific_objectives_feedback', models.TextField(blank=True, null=True)),
                ('methodology_feedback', models.TextField(blank=True, null=True)),
                ('expected_output_feedback', models.TextField(blank=True, null=True)),
                ('sustainability_plan_feedback', models.TextField(blank=True, null=True)),
                ('org_staffing_feedback', models.TextField(blank=True, null=True)),
                ('work_plan_feedback', models.TextField(blank=True, null=True)),
                ('budget_requirements_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_history', to='proposals_node.proposal')),
            ],
        ),
    ]
