# Generated by Django 5.2.11 on 2026-02-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_proposalreviewhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalreviewhistory',
            name='decision',
        ),
        migrations.AlterField(
            model_name='proposalreviewhistory',
            name='review_round',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
