# Generated by Django 5.2.11 on 2026-03-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_remove_proposalreviewhistory_decision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalreview',
            name='proposal_type',
            field=models.CharField(blank=True, choices=[('program', 'Program'), ('project', 'Project'), ('activity', 'Activity')], max_length=20, null=True),
        ),
    ]
