# Generated by Django 5.2.11 on 2026-03-06 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0005_alter_proposalreviewer_proposal_type'),
        ('reviews', '0007_alter_proposalreview_proposal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalreviewhistory',
            name='proposal_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposal_reviewer_history', to='reviewer.proposalreviewer'),
        ),
    ]
