# Generated by Django 5.2.11 on 2026-03-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_proposalreviewhistory_proposal_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalreview',
            name='review_round',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
