# Generated by Django 5.2.11 on 2026-03-06 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals_node', '0002_alter_proposal_status'),
        ('reviewer', '0005_alter_proposalreviewer_proposal_type'),
        ('reviews', '0009_alter_proposalreview_review_round'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proposalreview',
            unique_together={('proposal_node', 'proposal_reviewer')},
        ),
    ]
