# Generated by Django 5.2.11 on 2026-02-14 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('proposal_type', models.CharField(blank=True, choices=[('Program', 'Program'), ('Project', 'Project'), ('Activity', 'Activity')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('under_review', 'Under Review'), ('for_review', 'Under Review'), ('for_revision', 'For Revision'), ('for_approval', 'For Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='under_review', max_length=20)),
                ('version_no', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
