# Generated by Django 5.2.11 on 2026-02-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals_node', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('for_review', 'For Review'), ('under_review', 'Under Review'), ('for_revision', 'For Revision'), ('for_approval', 'For Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='for_review', max_length=20),
        ),
    ]
