# Generated by Django 5.2.11 on 2026-03-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals_node', '0002_alter_proposal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('for_review', 'For Review'), ('under_review', 'Under Review'), ('for_revision', 'For Revision'), ('for_approval', 'For Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='for_review', max_length=20),
        ),
    ]
