# Generated by Django 5.2.11 on 2026-03-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals_node', '0003_proposal_progress_alter_proposal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='budget_approved',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
