# Generated by Django 5.2.11 on 2026-03-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals_node', '0004_proposal_budget_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('used_budget', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
