# Generated by Django 5.2.11 on 2026-03-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals_node', '0005_yearconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearconfig',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='yearconfig',
            name='used_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
