# Generated by Django 5.2.11 on 2026-03-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals_node', '0006_alter_yearconfig_total_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='trigger_review_reset',
            field=models.BooleanField(default=False),
        ),
    ]
