# Generated by Django 5.2.11 on 2026-03-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals_node', '0007_proposal_trigger_review_reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('for_review', 'For Review'), ('under_review', 'Under Review'), ('for_revision', 'For Revision'), ('for_approval', 'For Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
