# Generated by Django 5.2.11 on 2026-02-14 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_proposal', '0001_initial'),
        ('proposals_node', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_title', models.CharField(max_length=255)),
                ('project_leader', models.CharField(blank=True, max_length=255, null=True)),
                ('members', models.JSONField(blank=True, default=list)),
                ('activity_duration_hours', models.IntegerField(blank=True, null=True)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('implementing_agency', models.JSONField(blank=True, null=True)),
                ('cooperating_agencies', models.JSONField(blank=True, null=True)),
                ('extension_sites', models.JSONField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('clusters', models.JSONField(blank=True, null=True)),
                ('agendas', models.JSONField(blank=True, null=True)),
                ('sdg_addressed', models.CharField(blank=True, max_length=255, null=True)),
                ('mandated_academic_program', models.CharField(blank=True, max_length=255, null=True)),
                ('rationale', models.TextField(blank=True, null=True)),
                ('significance', models.TextField(blank=True, null=True)),
                ('objectives_of_activity', models.TextField(blank=True, null=True)),
                ('methodology', models.CharField(blank=True, max_length=255, null=True)),
                ('expected_output_6ps', models.JSONField(blank=True, null=True)),
                ('sustainability_plan', models.TextField(blank=True, null=True)),
                ('org_and_staffing', models.JSONField(blank=True, null=True)),
                ('plan_of_activity', models.JSONField(blank=True, null=True)),
                ('budget_requirements', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='project_proposal.projectproposal')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_details', to='proposals_node.proposal')),
            ],
        ),
    ]
