# Generated by Django 5.2.11 on 2026-02-17 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_proposal', '0002_activityproposalhistory'),
        ('project_proposal', '0002_projectproposalhistory'),
        ('proposals_node', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityproposalhistory',
            name='project_proposal_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_history', to='project_proposal.projectproposalhistory'),
        ),
        migrations.AddField(
            model_name='activityproposalhistory',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_history', to='proposals_node.proposal'),
        ),
    ]
