# Generated by Django 5.2.11 on 2026-02-27 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_proposal', '0003_activityproposalhistory_project_proposal_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityproposalhistory',
            name='project_proposal_history',
        ),
    ]
