# Generated by Django 5.2.11 on 2026-03-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_proposal', '0004_remove_activityproposalhistory_project_proposal_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityproposalhistory',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
