# Generated by Django 5.2.11 on 2026-02-14 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proposals_node', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalCoverPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_page_body', models.TextField(blank=True, null=True)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cover_details', to='proposals_node.proposal')),
            ],
        ),
    ]
