# Generated by Django 5.2.11 on 2026-02-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_proposal', '0002_projectproposalhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectproposal',
            name='activity_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
