# Generated by Django 5.2.11 on 2026-02-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_proposal', '0003_projectproposal_activity_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectproposalhistory',
            name='activity_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
