# Generated by Django 5.2.11 on 2026-02-27 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_proposal', '0004_projectproposalhistory_activity_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectproposalhistory',
            name='program_proposal_history',
        ),
    ]
