# Generated by Django 5.2.11 on 2026-03-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_proposal', '0005_remove_projectproposalhistory_program_proposal_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectproposalhistory',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
