# Generated by Django 5.2.11 on 2026-03-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_proposal', '0006_projectproposalhistory_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectproposal',
            name='methodology',
            field=models.TextField(blank=True, null=True),
        ),
    ]
